name: dokan_demo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
    

flutter:


  uses-material-design: true
  assets:
    - assets/images/
flutter_native_splash:
      android: true
      ios: true
      web: false
      image: assets/images/logo.png
      color: "#030939"
      color_dark: "#030939"
      image_dark: assets/images/logo.png
      android_12:
        image: assets/images/logo.png
        icon_background_color: "#030939"
        image_dark: assets/images/logo.png
        icon_background_color_dark: "#030939"